### ISSUE TITLE
We don't notice if qemu crashes or refuses to start

### ISSUE THREAD

**Issue by madworx** [madworx/docker-netbsd#16]
Improved trap/wait handling needed.

**Comment by madworx** [comment]
```
bash-4.4# set
SYSTEM_MEMORY=536870912
bash-4.4# /docker-entrypoint.sh
rpcbind: another rpcbind is already running. Aborting
bind: Address in use
Couldn't bind to tcp port 2049
Warning: Lacking KVM support - slower(!) emulation will be used.
NetBSD 8.0 [QEMU]: cannot set up guest memory 'pc.ram': Out of memory
bash-4.4# exit
```

**Comment by wtchappell** [comment]
I think I was actually bitten by this just the other day; I had a container get to the KVM status message step but I don't think it ever actually successfully started QEMU. Being able to get the error output from QEMU - or a log of how far the VM's console got - would be extremely helpful.

**Comment by wtchappell** [comment]
Where is the following bit coming from?

```bind: Address in use
Couldn't bind to tcp port 2049```

**Comment by madworx** [comment]
It indicates that nfsd can't bind port 2049; Either another nfsd is already running, some other software running that has bound 2049, or possibly a bug in nfsd. I had to do some patching on the bundled nfsd to make it work on recent versions of the Linux kernel.

In which situation do you get this error message?

**Comment by madworx** [comment]
It also seems that the madworx/qemu container (which the madworx/netbsd one is based off of) has a broken buildchain. I'll look into both projects this weekend.

**Comment by madworx** [comment]
The builds have now been restored to working condition via PR #25 .

**Comment by madworx** [comment]
qemu crash detection is now implemented in bsd.sh, qemu has been upgraded to version 7 and virtio networking will work as soon as NetBSD HEAD resolves this issue: https://mail-index.netbsd.org/netbsd-bugs/2022/09/24/msg076161.html
