### ISSUE TITLE
`docker pull madworx/netbsd` fails: manifest for madworx/netbsd:latest not found

### ISSUE THREAD

**Issue by timotheecour** [madworx/docker-netbsd#24]
```
docker pull madworx/netbsd
Using default tag: latest
Error response from daemon: manifest for madworx/netbsd:latest not found: manifest unknown: manifest unknown
```

am I missing something obvious?
I'm on OSX and other commands work (eg docker pull phusion/baseimage)

EDIT: this works: `docker pull madworx/netbsd:8.0-x86_64` but not sure whether `docker pull madworx/netbsd` is supposed to work or not

**Comment by madworx** [comment]
My idea was to encapsulate the fact that the emulated target is "x86_64" -- I've removed that part of the tag recently and if you're still using these images, I'd suggest pulling the ones without the `-x86_64` suffix, since the newer ones are built on QEMU 7.
