### ISSUE TITLE
Images not usable as GitLab CI/CD images

### ISSUE THREAD

**Issue by jas4711** [madworx/docker-netbsd#26]
Thanks for providing NetBSD docker images!  I was surprised it was so hard to find them, and that there aren't any official docker images of NetBSD.

My use of them are to test build my projects via GitLab, and I tried setting this up for GNU SASL on this commit:

https://git.savannah.gnu.org/cgit/gsasl.git/commit/?id=b742a7bff2b4f8db2230fe6ef68ca46a4b51da01

However running fails:

https://gitlab.com/gsasl/gsasl-cicd/-/jobs/929128616

Do you have any ideas how to modify the docker images to make them usable as GitLab CI/CD docker images?  The reference to bash makes me suspect that GitLab somehow create a bash script of my 'before_script' commands and attempts to invoke that.  Unfortunately my knowledge of how GitLab CI/CD works on the server-side is too limited to help.

Thanks.

**Comment by abartlet** [comment]
This would be very useful for Samba, if it were to become possible. 

Sadly the docker entrypoint does not map the arguments into something run inside the image, outputting on stdout etc, it just boots the VM which waits for an SSH connection.

A lot more work would be needed for the Gitlab CI use case, mostly in terms of mapping the host filesystem into the VM and then finding a way to, say via the kernel command line, start the commands required.

**Comment by madworx** [comment]
I have reworked some parts of how to interact with the container, as well as providing better documentation on how to map host filesystem into the NetBSD container.

If the documentation is unclear on how to make the image work, please open another PR and explain the use-case. (I.e. how does Gitlab actually try to invoke the container?)
