### ISSUE TITLE
NetBSD current or NetBSD 9.2?

### ISSUE THREAD

**Issue by jbglaw** [madworx/docker-netbsd#27]
Hi!

I just found this Docker container and it could could be extremely helpful! Hard to find actually.

However, the newest build is NetBSD 9.0 based. Any chance you'd update to latest or at least 9.2?

Thanks,
  Jan-Benedict

**Comment by madworx** [comment]
I've implemented support for building using current HEAD (up-coming 10) and bumped the default version to 9.3.

**Comment by madworx** [comment]
@jbglaw: Also might mention that you can set NETBSD_SETS if you wish to add more base sets when building the image, and set NETBSD_PKGSRC_PACKAGES if you want to install additional packages from pkgsrc.
