### ISSUE TITLE
Proper stdin/stdout?

### ISSUE THREAD

**Issue by jbglaw** [madworx/docker-netbsd#28]
Hi!

It seems I cannot get stdin properly to the container. I've got a lot of scripts using Docker containers in this way: Some shell/interpreter is started and the script to be executed is given as a here document. This does somehow not work with the NetBSD container.

```
# docker --rm -it ... madworx/netbsd:9.0-x86_64" /usr/pkg/bin/bash << 'HEREDOC'
echo Build commands here
HEREDOC
```

Any chance to get this working?

Thanks,
  Jan-Benedict

**Comment by jbglaw** [comment]
I *think* that the issue is with `bsd.sh`: While it tries to connect to the booting VM, those `ssh` calls don't have `< /dev/null` and zap away all stdin I think.

**Comment by madworx** [comment]
Interesting. I'll investigate, but my first guess would be that some process/shell along the way munches up the data you're trying to provide before the VM has actually started. (I faced similar issues with the madworx/minix images which lead me to use expect scripts instead).

**Comment by madworx** [comment]
(... which, to be honest, was pretty much what you wrote above :-). I'll apply that and check if that fixes the issue.)
